### ISSUE TITLE
Refresh data on table (Order, filter) with ember 2.8

### ISSUE THREAD

**Issue by lypborges** [offirgolan/ember-light-table#231]
First, good job! If I be able to put on my project will save me a lot of time.

I'm using ember 2.8 and try to use like the [docs show.](http://offirgolan.github.io/ember-light-table/docs/modules/Table%20Declaration.html) 

```

import Ember from 'ember';
import Table from 'ember-light-table';

const { computed } = Ember;

export default Ember.Component.extend({
  store: Ember.inject.service(),
  page: 1,
  limit: 20,
  dir: 'asc',
  sort: null,
  model: null,

  columns: null,
  table:  computed('model', function() {
    return new Table(this.get('columns'), this.get('model'), { enableSync: true });
  }),

  fetchRecords() {
    this.get('store').query('person', this.getProperties(['page', 'limit', 'sort', 'dir'])).then(records => {
      this.get('model').pushObjects(records.toArray());
    });
  },
  actions: {
    onColumnClick(column) {
      if (column.sorted) {
        this.setProperties({
          dir: column.ascending ? 'asc' : 'desc',
          sort: column.get('valuePath'),
          page: 1
        });
        this.get('model').clear();
        this.fetchRecords();
      }
    }
  }

});
```

But I'm getting this error when I try order the table.
>ember.debug.js:19157 TypeError: internalModel.getRecord is not a function
    at Class.objectAtContent (record-array.js:86)
    at Class.objectAt (ember.debug.js:37639)
    at Object.objectAt (ember.debug.js:33683)
    at Class.contentDidChange (ember.debug.js:7582)
    at Object.sendEvent (ember.debug.js:19414)
    at arrayContentDidChange (ember.debug.js:33764)
    at Class._emberMetalMixin.Mixin.create._Mixin$create.arrayContentDidChange (ember.debug.js:33931)
    at Class.arrangedContentArrayDidChange (ember.debug.js:37761)
    at Object.applyStr (ember.debug.js:24978)
    at Object.sendEvent (ember.debug.js:19408)

If i try change only the fechRecords method I'm getting a diferente error
```
  fetchRecords() {
    this.get('store').query('person', this.getProperties(['page', 'limit', 'sort', 'dir'])).then(records => {
      this.get('store').push(records);
    });
  },
````
>ember.debug.js:19157 Error: Assertion Failed: Expected an object in the 'data' property in a call to 'push' for maestro@model:person:, but was undefined
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:29207:21)
    at assert (http://localhost:4200/assets/vendor.js:16905:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:29019:34)
    at assert (http://localhost:4200/assets/vendor.js:142166:37)
    at Class.push (http://localhost:4200/assets/vendor.js:151384:41)
    at http://localhost:4200/assets/maestro.js:213:28
    at tryCatch (http://localhost:4200/assets/vendor.js:61077:14)
    at invokeCallback (http://localhost:4200/assets/vendor.js:61092:15)
    at publish (http://localhost:4200/assets/vendor.js:61060:9)

What I'm missing? What is the right way?

**Comment by buschtoens** [comment]
Please take a look at #224. If you need further assistance, I'm here.

**Comment by offirgolan** [comment]
Closing in favor of #224. Feel free to reopen.
