### ISSUE TITLE
Cannot load table

### ISSUE THREAD

**Issue by domgolonka** [offirgolan/ember-light-table#333]
Hello,

I've copied one of the examples but the tables won't load and instead gives an error:

> Uncaught TypeError: _emberLightTable2.default is not a constructor
    at Class.init (TableCommonMixin.js:23)
    at Class.superWrapper [as init] (ember.debug.js:24805)
    at new Class (ember.debug.js:37912)
    at Function.create (ember.debug.js:38172)
    at createComponent (ember.debug.js:14109)
    at Function.ComponentNodeManager_create [as create] (ember.debug.js:13993)
    at Object.componentHook [as component] (ember.debug.js:10393)
    at handleRedirect (ember.debug.js:45239)
    at Object.range (ember.debug.js:45548)
    at Object.content (ember.debug.js:45944)
ember.debug.js:6628 DEPRECATION: You modified undefined twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 3.0 [deprecation id: ember-views.render-double-modify]
        at logDeprecationStackTrace (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.bower.js:17194:20)
        at HANDLERS.(anonymous function) (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.bower.js:17304:8)
        at raiseOnDeprecation (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.bower.js:17224:13)
        at HANDLERS.(anonymous function) (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.bower.js:17304:8)
        at invoke (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.bower.js:17320:8)
        at deprecate (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.bower.js:17288:33)
        at Object.deprecate (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.bower.js:29495:38)
        at Class.exports.default._emberMetalMixin.Mixin.create._Mixin$create.scheduleRevalidate (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.bower.js:53529:27)
        at chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.bower.js:27712:20
logDeprecationStackTrace @ ember.debug.js:6628

TableCommonMixin.js:

```
import { Mixin, inject, isEmpty } from "Ember";
     import Table from "ember-light-table";
     export default Mixin.create({
	store: inject.service(),
	page: 0,
	limit: 10,
	dir: "asc",
	sort: "username",
	isLoading: false,
	canLoadMore: true,
        
	model: "serverAccounts",
	columns: `{username, password, pincode, centcoin}`,
	table: "accounts",

	init() {
		this._super(...arguments);

		let table = new Table(this.get("columns"), this.get("model"), { enableSync: true });
		let sortColumn = table.get("allColumns").findBy("valuePath", this.get("sort"));

		// Setup initial sort column
		if (sortColumn) {
			sortColumn.set("sorted", true);
		}

		this.set("table", table);
	},

	fetchRecords() {
		this.set("isLoading", true);
		this.get("store").query("user", this.getProperties(["page", "limit", "sort", "dir"]))
			.then((records) => {
			this.get("model").pushObjects(records.toArray());
			this.set("canLoadMore", !isEmpty(records));
		}).finally(() => {
			this.set("isLoading", false);
		});
	},

	actions: {
		onScrolledToBottom() {
			if (this.get("canLoadMore")) {
				this.incrementProperty("page");
				this.fetchRecords();
			}
		},

		onColumnClick(column) {
			if (column.sorted) {
				this.setProperties({
					dir: column.ascending ? "asc" : "desc",
					sort: column.get("valuePath"),
					canLoadMore: true,
					page: 0
				});
				this.get("model").clear();
			}
		}
	}
  });
```

AccountsTableComponent.js:
```
import { computed, Component } from "Ember";

  import layout from "templates/components/tables/AccountsTableComponent.hbs";

  import TableCommonMixin from "mixins/TableCommonMixin";
  export default Component.extend(TableCommonMixin,{
	layout,
	columns: computed(function() {
		return [{
			label: "Username",
			valuePath: "username",
			width: "150px"
		}, {
			label: "Password",
			valuePath: "password",
			width: "150px"
		}];
	})
  });

```

AccountsTableComponent.hbs:

```

   {{#light-table table height='65vh' as |t|}}
    {{t.head
        onColumnClick=(action 'onColumnClick')
        iconAscending='fa fa-sort-asc'
        iconDescending='fa fa-sort-desc'
        fixed=true
    }}

    {{#t.body
        canSelect=false
        onScrolledToBottom=(action 'onScrolledToBottom')
    as |body|
    }}
        {{#if isLoading}}
            {{#body.loader}}
                {{table-loader}}
            {{/body.loader}}
        {{/if}}
    {{/t.body}}
   {{/light-table}}
```

**Comment by buschtoens** [comment]
Closing this as well, https://github.com/offirgolan/ember-light-table/issues/334#issuecomment-308752275.

Again, if you still experience these problems, don't hesitate to comment on one of your issues. :slightly_smiling_face:
