### ISSUE TITLE
error after upgrade ember 3.11 in new Table(...)

### ISSUE THREAD

**Issue by schekin** [offirgolan/ember-light-table#706]
Error: Assertion Failed: An EmberObject based class, (unknown), was not instantiated correctly. You may have either used `new` instead of `.create()`, or not passed arguments to your call to super in the constructor: `super(...arguments)`. If you are trying to use `new`, consider using native classes without extending from EmberObject.
    at assert (http://localhost:4200/assets/vendor.js:53858:17)
    at new CoreObject (http://localhost:4200/assets/vendor.js:47113:33)
    at new EmberObject (http://localhost:4200/assets/vendor.js:47979:3)
    at new Class (http://localhost:4200/assets/vendor.js:47492:19)
    at new Table (http://localhost:4200/assets/vendor.js:204975:7)
    at Class.<anonymous> (/home/schekin/Projects/piomni/piomni-client/app/mixins/peek-table.js:50:17)
    at ComputedProperty.get (http://localhost:4200/assets/vendor.js:33785:28)
    at get (http://localhost:4200/assets/vendor.js:32911:27)
    at RootPropertyReference.compute (http://localhost:4200/assets/vendor.js:19212:30)
    at RootPropertyReference.value (http://localhost:4200/assets/vendor.js:19068:43)

` init() {
    this._super(...arguments);
    
    this.set("modelTable",this.get('model').toArray());
    let table = new Table(this.get('columns'),this.get("modelTable"), { enableSync: this.get('enableSync') });
    let sortColumn = table.get('allColumns').findBy('valuePath', this.get('sort'));`

**Comment by fran-worley** [comment]
Thanks for getting in touch - we're aware of this, please see the fix in this PR https://github.com/offirgolan/ember-light-table/pull/701

**Comment by lougreenwood** [comment]
I don't think this should be a closed issue until the PR is merged.

I've been tracking down this issue all afternoon and only just stumbled across the issue & PR by accident.
